"""Normalized data types shared between the radio layer and the UI.

The meshtastic library hands us loosely-typed dicts straight off the wire.
Everything crossing into the UI gets converted to one of these first, so the
widgets never have to know about protobuf field names.
"""

from __future__ import annotations

import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

BROADCAST = "^all"
SPARK_WIDTH = 8

# Fallback if the protobuf constant cannot be read; radio.max_payload_bytes()
# prefers the value compiled into the installed meshtastic library.
DEFAULT_MAX_PAYLOAD = 233
MESHCORE_MAX_PAYLOAD = 133


@dataclass(frozen=True)
class ChannelRef:
    """A real protocol channel slot, never a position in a filtered list."""

    protocol: str
    index: int
    name: str = ""


@dataclass(frozen=True)
class PeerRef:
    """A protocol peer suitable for a direct message."""

    protocol: str
    node_id: str
    # MeshCore uses the full X25519 public key internally.  The UI's !xxxxxxxx
    # label remains useful for display, but must not be the only durable identity.
    public_key: str | None = None


DestinationRef = ChannelRef | PeerRef


class DeliveryStatus(str, Enum):
    QUEUED = "queued"
    SENT = "sent"
    DELIVERED = "delivered"
    FAILED = "failed"
    EXPIRED = "expired"


@dataclass
class SendReceipt:
    """Protocol-neutral progress for one outbound message.

    `message_id` is generated by meshtui and survives retries/restarts;
    `protocol_id` is the Meshtastic packet id or MeshCore expected-ACK code.
    """

    message_id: str
    destination: DestinationRef
    status: DeliveryStatus
    protocol_id: int | str | None = None
    detail: str = ""
    updated_ts: float = field(default_factory=time.time)

    @property
    def accepted(self) -> bool:
        return self.status not in (DeliveryStatus.FAILED, DeliveryStatus.EXPIRED)

    @classmethod
    def queued(cls, destination: DestinationRef, message_id: str | None = None) -> "SendReceipt":
        return cls(message_id or uuid.uuid4().hex, destination, DeliveryStatus.QUEUED)


def outgoing_payload(entry: str) -> str | None:
    """The text that a chat entry would actually transmit.

    Returns None for entries that never reach the air (local slash commands),
    so the byte counter and the length check can ignore them.
    """
    entry = entry.strip()
    if not entry:
        return None
    if entry.startswith("/"):
        parts = entry.split(maxsplit=2)
        if parts[0].lower() == "/dm":
            # "/dm <node> <text>" - only <text> is transmitted.
            return parts[2] if len(parts) >= 3 else ""
        return None
    return entry


def payload_bytes(text: str) -> int:
    """Meshtastic limits the payload in BYTES, so multi-byte characters
    (accents, emoji) cost more than one each."""
    return len(text.encode("utf-8"))

# portnum -> (short label, colour) for the packet feed
PORT_STYLES: dict[str, tuple[str, str]] = {
    "TEXT_MESSAGE_APP": ("TEXT", "bright_white"),
    "POSITION_APP": ("POS", "cyan"),
    "NODEINFO_APP": ("NODE", "green"),
    "TELEMETRY_APP": ("TELEM", "yellow"),
    "ROUTING_APP": ("ROUTE", "magenta"),
    "ADMIN_APP": ("ADMIN", "red"),
    "TRACEROUTE_APP": ("TRACE", "bright_magenta"),
    "NEIGHBORINFO_APP": ("NEIGH", "bright_blue"),
    "WAYPOINT_APP": ("WAYPT", "bright_cyan"),
    "STORE_FORWARD_APP": ("STOR", "blue"),
    "RANGE_TEST_APP": ("RANGE", "bright_yellow"),
    "DETECTION_SENSOR_APP": ("DETECT", "orange1"),
    "PRIVATE_APP": ("PRIV", "grey62"),
}


def port_label(portnum: str) -> tuple[str, str]:
    if portnum in PORT_STYLES:
        return PORT_STYLES[portnum]
    return (portnum.replace("_APP", "")[:6] or "?", "grey62")


@dataclass
class Packet:
    """One received packet, flattened for display."""

    ts: float
    from_id: str
    to_id: str
    portnum: str
    summary: str
    channel: int = 0
    snr: float | None = None
    rssi: int | None = None
    hops: int | None = None
    packet_id: int | None = None
    encrypted: bool = False
    # Low byte of the node number that relayed this packet to us. The only
    # routing evidence a packet carries, and enough to build a real graph.
    relay_node: int | None = None
    via_mqtt: bool = False
    # Set when a PUBLISHED key decrypted this packet - never a recovered secret.
    decrypted_with: str | None = None
    raw: dict[str, Any] = field(default_factory=dict)

    @property
    def is_broadcast(self) -> bool:
        return self.to_id in (BROADCAST, "!ffffffff")


@dataclass
class Node:
    """A node in the mesh, merged from NodeDB snapshots and live packets."""

    num: int
    node_id: str
    long_name: str = ""
    short_name: str = ""
    hw_model: str = ""
    role: str = ""
    snr: float | None = None
    rssi: int | None = None
    hops: int | None = None
    battery: int | None = None
    voltage: float | None = None
    ch_util: float | None = None
    air_util: float | None = None
    uptime: int | None = None
    lat: float | None = None
    lon: float | None = None
    alt: int | None = None
    last_heard: float | None = None
    first_seen: float = field(default_factory=time.time)
    packets: int = 0
    is_self: bool = False
    via_mqtt: bool = False
    # Recent per-packet SNR readings, oldest first, for the trend sparkline.
    snr_history: deque[float] = field(default_factory=lambda: deque(maxlen=SPARK_WIDTH))

    # Motion, from POSITION_APP. Meshtastic sends ground_speed in m/s and
    # ground_track scaled by 1e5 - note the protobuf comment claims 1/100
    # degrees, but real traffic (e.g. 23714000 -> 237.14 deg) says otherwise.
    speed_mps: float | None = None
    heading_deg: float | None = None
    sats: int | None = None
    location_source: str = ""
    # Bits of lat/lon precision the sender chose to keep. Fewer bits means the
    # node is deliberately fuzzing its position.
    precision_bits: int | None = None
    track: deque[tuple[float, float, float]] = field(default_factory=lambda: deque(maxlen=40))

    # Latest environment / air-quality readings, and the node's own mesh stats.
    env: dict[str, float] = field(default_factory=dict)
    env_ts: float | None = None
    local_stats: dict[str, float] = field(default_factory=dict)
    local_stats_ts: float | None = None

    @property
    def name(self) -> str:
        return self.long_name or self.short_name or self.node_id

    @property
    def label(self) -> str:
        """Short display name, preferring the 4-char short name."""
        return self.short_name or self.long_name[:8] or self.node_id[-4:]

    @property
    def age(self) -> float | None:
        if self.last_heard is None:
            return None
        return max(0.0, time.time() - self.last_heard)

    @property
    def has_position(self) -> bool:
        return self.lat is not None and self.lon is not None

    @property
    def moving(self) -> bool:
        return bool(self.speed_mps and self.speed_mps >= 1)

    @property
    def precision_metres(self) -> float | None:
        """Quantisation step implied by precision_bits, in metres.

        Meshtastic zeroes the low (32 - precision_bits) bits of the 1e-7 degree
        latitude integer, so the step is 2^(32-bits) * 1e-7 degrees.
        """
        if self.precision_bits is None or self.precision_bits >= 32:
            return None
        step_deg = (2 ** (32 - self.precision_bits)) * 1e-7
        return step_deg * 111320.0


@dataclass
class ChatMessage:
    ts: float
    from_id: str
    from_name: str
    to_id: str
    text: str
    channel: int = 0
    outgoing: bool = False
    packet_id: int | None = None
    acked: bool = False
    message_id: str | None = None
    delivery_status: str = ""
    # For our own channel messages: repeaters heard rebroadcasting it, and the
    # packet hash that ties every repeat to this message. Populated live as the
    # repeats arrive over the air, the way the phone apps show it.
    repeated_by: set = field(default_factory=set)
    repeat_pkt: int | None = None

    @property
    def is_dm(self) -> bool:
        return self.to_id not in (BROADCAST, "!ffffffff")
